export enum ETypes {
	Normal = 'Normal',
	Fire = 'Fire',
	Water = 'Water',
	Electric = 'Electric',
	Grass = 'Grass',
	Ice = 'Ice',
	Fighting = 'Fighting',
	Poison = 'Poison',
	Ground = 'Ground',
	Flying = 'Flying',
	Psychic = 'Psychic',
	Bug = 'Bug',
	Rock = 'Rock',
	Ghost = 'Ghost',
	Dragon = 'Dragon',
	Dark = 'Dark',
	Steel = 'Steel',
}

export const typesMapColor: Record<ETypes, string> = {
	[ETypes.Normal]: '#CACACA',
	[ETypes.Fire]: '#ED7F37',
	[ETypes.Water]: '#3EAFF6',
	[ETypes.Electric]: '#FCEF2C',
	[ETypes.Grass]: '#78C850',
	[ETypes.Ice]: '#66D1E5',
	[ETypes.Fighting]: '#81221B',
	[ETypes.Poison]: '#A14CA0',
	[ETypes.Ground]: '#CA9F5E',
	[ETypes.Flying]: '#A890F0',
	[ETypes.Psychic]: '#E65386',
	[ETypes.Bug]: '#A8B820',
	[ETypes.Rock]: '#898373',
	[ETypes.Ghost]: '#805594',
	[ETypes.Dragon]: '#796BF8',
	[ETypes.Dark]: '#3c2d23',
	[ETypes.Steel]: '#E4E4E4',
}